name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Stop application if running
        id: stop_if_running
        uses: appleboy/ssh-action@master
        if: success() && steps.check_process.outputs.running == 'true'
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if pgrep -f "/home/g2nee/target/delivery-0.0.1-SNAPSHOT.jar"; then
              pkill -f /home/g2nee/target/delivery-0.0.1-SNAPSHOT.jar
            fi

      - name: Check if files exist in target directory
        run: |
          if [ -z "$(ls -A target/delivery-0.0.1-SNAPSHOT.jar 2>/dev/null)" ]; then
            rm target/delivery-0.0.1-SNAPSHOT.jar
          fi

      - name: Upload file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "target/*.jar"
          target: "~/"
          rm: false

      - name: Execute shell script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: "./startupdelivery.sh"
